services:
  ### LLM: Ollama self-host
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - hrnet

  ### Qdrant: vector DB
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - hrnet

  ### PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: hradmin
      POSTGRES_PASSWORD: hrpass
      POSTGRES_DB: hr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hrnet

  ### Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - hrnet

  ### Redis (cache + queue)
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hrnet

  ### CV worker
  cv_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv_worker
    working_dir: /app
    depends_on:
      - redis
      - postgres
    environment:
      POSTGRES_URI: postgresql://hradmin:hrpass@postgres/hr_db
      REDIS_HOST: redis
    networks:
      - hrnet
      
  tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    depends_on:
      - redis
      - postgres
      - cv_worker
    environment:
      POSTGRES_URI: postgresql://hradmin:hrpass@postgres/hr_db
    volumes:
      - .:/app
    networks:
      - hrnet

volumes:
  ollama_data:
  qdrant_data:
  postgres_data:
  es_data:
  redis_data:

networks:
  hrnet:
